### ISSUE TITLE
Can't create a new project

### ISSUE THREAD

**Issue by resisttheurge** [tyleranton/crockpot#1]
I created an account, entered the project name `scrubware`, clicked the `Create Project` button, and nothing happened. 

plz halp my entprise depends on this

**Comment by Shozaku** [comment]
I would like to know too if a fix is found.

If only this project had dependable developers! 1/10

**Comment by tyleranton** [comment]
I can't reproduce the issue. You noobs can get rekt.

**Comment by Shozaku** [comment]
I'm unsure of what to make of this, the developer clearly doesn't trust his only customers. As loyal as I am, I am forced to leave this shitty site as the developer thinks it's a funny joke to insult us and our one and only lord and savior The Glorious Fucking Zun :zun:

![image](https://cloud.githubusercontent.com/assets/5942019/6743143/42e1d772-ce64-11e4-9eea-2f0eed6a2896.png)

**Comment by tyleranton** [comment]
I accept your apology...scrub.
